config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/sign_in', to: 'devise/sessions#new'
  post '/users/:id', to: 'devise/sessions#create'
  resources :sessions, only: [:new, :create, :destroy, :omniauth, :auth]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :trips
  resources :locations
  resources :comments
  resources :users, only: [:show] do 
    resources :trips, only: [:index, :show, :new, :create, :edit, :update]
  end 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base 
    belongs_to :user 
    belongs_to :trip
    validates :content, presence: true 
end 

app/models/location.rb
class Location < ActiveRecord::Base 
    attr_accessor :city, :state, :zipcode
    has_many :trips
    has_many :users, through: :trips
    validates :city, :state, :zipcode, presence: true
    validates :zipcode, numericality: { only_integer: true }
    validates :zipcode, length: { is: 5 }
end

app/models/trip.rb
class Trip < ActiveRecord::Base 
    belongs_to :user 
    has_many :location
    accepts_nested_attributes_for :location
    has_many :comments 
    validates :title, presence: true 
    validates :content, presence: true 
end 

app/models/user.rb
class User < ActiveRecord::Base 
    has_many :trips 
    has_many :locations, through: :trips 
    has_many :comments 
    validates :first_name, :last_name, :email, presence: true  
    validates :email, uniqueness: true
    has_secure_password 
    validates :password_digest, presence: true 

    devise  :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :confirmable, :lockable, :timeoutable,
    :omniauthable, omniauth_providers: [:google_oauth2]

    def self.create_from_provider_data(provider_data)
        where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do | user |
          user.email = provider_data.info.email
          user.password = Devise.friendly_token[0, 20]
          user.skip_confirmation!
        end
    end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    protect_from_forgery with: :exception
    before_action :login_required
    skip_before_action :login_required, only: [:new, :create]

    def login_required
        if !logged_in? 
            redirect_to new_session_path, :notice => "Log in to edit or delete your ratings"
        end 
    end 

    def logged_in?
        !current_user.nil?
    end 

    helper_method :logged_in?
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController 
    def index 
        @comments = Comment.all
    end 

    def show 
        @comment = Comment.find(params[:id])
    end 

    def new 
        @comment = Comment.new(comment_params)
    end 
    
    def create 
        if @comment.valid? 
            @comment.save
            redirect_to comment_path(@comment)
        else 
            render :new 
        end 
    end 

    # def edit 
    #     @comment = Comment.find(params[:id])
    # end 

    # def update 
    #     if @comment.update(comment_params)
    #         redirect_to comment_path(@comment)
    #     else 
    #         render :edit 
    #     end 
    # end 

    # def destroy 
    #     if @comment.destroy
    #         redirect_to user_path(current_user)
    #         flash[:message] = "Your comment was deleted."
    #     else 
    #         flash[:message] = "You can't delete other user's comments."
    #         redirect_to trip_path(@comment)
    #     end 
    # end 

    private 

    def comment_params 
        params.require(:comment).permit(:content)
    end 

end 

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    def index 
        @locations = Location.all 
    end 

    def show 
        @location = Location.find(params[:id])
    end 

    def new 
        @location = Location.new(location_params)
    end 

    def create 
        if @location.valid? 
            @location.save 
            redirect_to location_path(@location)
        else 
            render :new
        end 
    end 

    def edit 
        @location = Location.find(params[:id])
    end 

    def update 
        if @location.update(location_params)
            redirect_to location_path(@location)
        else 
            render :edit 
        end
    end 

    def destroy 
    end 

    private 
    
    def location_params 
        params.require(:location).permit(:city, :state, :zipcode)
    end 
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
   
    def new 
        if logged_in?
            redirect_to user_path(current_user)
        end
    end 

    def omniauth 
        user = User.create_from_omniauth(auth)
        if user.valid?
           session[:user_id] = user.id
           redirect_to user_path(user.id)
       else
           flash[:message] = "#{user.errors.full_messages.join("")}."
           redirect_to login_path
       end
   end 

    def create 
        @user = User.find_by(email: params[:email])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else 
            flash[:alert] = "Email or Password you entered was invalid."
            redirect_to login_path
        end 
    end 


    def destroy 
        session.delete(:user_id)
        redirect_to login_path
    end 

    private 

    def auth 
        request.env['omniauth.auth']
    end 
end 

app/controllers/trips_controller.rb
class TripsController < ApplicationController 
    def index 
        if params[:user_id]
            @trips = User.find(params[:user_id]).trips 
        else 
            @trips = Trip.all
        end 
    end 

    def show
        @trip = Trip.find_by(params[:id]) 
    end 

    def new 
        @trip = Trip.new(user_id: params[:user_id])
    end 

    def create 
        @trip = Trip.create(trip_params)
        if  @trip.save 
            redirect_to trip_path(@trip)
        else 
            render :new 
        end 
    end 

    def edit 
        @trip = Trip.find_by(params[:id])
    end 
    
    def update 
        if @trip.update(trip_params)
            redirect_to trip_path(@trip)
        else 
            render :edit 
        end
    end 

    def destroy 
        Trip.find(params[:id]).destroy
        redirect_to user_trip_path
    end 

    private 

    def trip_params 
        params.require(:trip).permit(:title, :content, :user_id, location_attributes: [:city, :state, :zipcode])
    end 

end 

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
        @user = User.create_from_google_data(request.env['omniauth.auth'])
        if @user.persisted?
            sign_in_and_redirect @user
            set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
        else
            flash[:error] = 'There was a problem signing you in through Google. Please register or try signing in later.'
            redirect_to new_user_registration_url
        end 
    end

    def failure
        flash[:error] = 'There was a problem signing you in. Please register or try signing in later.' 
        redirect_to new_user_registration_url
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
    def index 
        @users = User.all
    end 

    def show 
        @user = User.find_by(params[:id])
    end 

    def new 
        @user = User.new
    end 

    def create 
        @user = User.create(user_params)
        if @user.save
           session[:user_id] = @user.id
           redirect_to user_path(@user)
        else 
            render :new 
        end
    end 

    private 

    def user_params 
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= render 'layouts/header' %>
<%= form_for @comment do |f| %> 
    <%= f.label :content %><br>
    <%= f.text_area :content %><br>

    <%= f.submit %> 
<% end %> 

app/views/comments/show.html.erb
<%= render 'layouts/header' %>
<h1><%= @comment.user.first_name %></h1> 
<p><%= @comment.user.content %><br> 

app/views/layouts/_header.html.erb
<% if logged_in? %> 
  <%= link_to "Homepage", user_path(:id) %> &nbsp
  <%= link_to "Create a New Trip", '/trips/new' %> &nbsp
  <%= link_to "View all Locations", '/locations' %> &nbsp 
  <%= link_to "View all Trips", '/trips' %> &nbsp
  <%= link_to "Logout", logout_path, method: "delete" %>&nbsp<br><br><br>
<% else %>
  <%= link_to “Login”, new_sessions_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeekenderSeattle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<%= render 'layouts/header' %>
<h1>All Locations</h1>
<h2><% @locations.each do |location|%></h2>
    <p><%= link_to location.city, location.state, location_path(location) %></p>
<% end  %> 

app/views/locations/show.html.erb
<%= render 'layouts/header' %>

app/views/trips/_form.html.erb
<% if @trip.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@trip.errors.count, "error") %>
    prohibited this trip from being saved:
  </h2>

  <ul>
  <% @trip.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

<%= form_for @trip do |f| %> 
    <%= f.label "Trip Title:" %><br> 
    <%= f.text_field :title %><br> 
    <%= f.hidden_field :user_id, value: current_user.id %>

    <%= f.fields_for  :locations do |l| %> 
        <%= l.label :city %><br>
        <%= l.text_field :city %><br>

        <%= l.label :state %><br> 
        <%= l.text_field :state %><br> 

        <%= l.label :zipcode %><br> 
        <%= l.text_field :zipcode %><br> 
    <% end %> 
 
    <%= f.label "Tell us what there is to do in the area:" %><br>
    <%= f.text_area :content %><br>
 
    <%= f.submit  %>
<% end %> 

app/views/trips/edit.html.erb
<%= render 'form' %>

app/views/trips/index.html.erb
<%= render 'layouts/header' %>
<%= button_to "Create A New Trip", new_trip_path, method: :get %>
<h1>All Trips</h1>
<h2><% @trips.each do |trip|%></h2>
    <p><%= link_to trip.title, trip_path(trip) %></p>
<% end  %> 

app/views/trips/new.html.erb
<%= render 'form' %>

app/views/trips/show.html.erb
<%= render 'layouts/header' %>
<h1><%= @trip.title %></h1><br>
<h2>Location:<%= @trip.location%></h2><br>
<h2>About This Trip: <%= @trip.content %></h2><br>

<%= button_to "Delete Trip", trip_path(@trip), method: :delete %> 

app/views/users/new.html.erb
<h1>Create Your Account</h1> 

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited your account from being created:
    </h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |f| %> 
    <%= f.label :first_name %><br> 
    <%= f.text_field :first_name %><br>

    <%= f.label :last_name %><br> 
    <%= f.text_field :last_name %><br>

    <%= f.label :email %><br> 
    <%= f.text_field :email %><br>

    <%= f.label :password %><br> 
    <%= f.password_field :password %><br> 

    <%= f.label :password_confirmation %><br> 
    <%= f.password_field :password_confirmation %><br>

    <%= f.submit "Create Account" %> 
<% end %>

app/views/users/show.html.erb
<%= render 'layouts/header' %>
<h1>Weekender</h1>

<h2>Current User: <%= current_user.first_name %><h2>

<%= button_to "Create New Trip", new_user_trip_path(@user), method: :get %>

<p>Trips:</p>
<% @user.trips.each do |trip| %> 
    <div><%= button_to trip.title %></div>
<% end %> 